spring:
  application:
    name: finsight-backend

  datasource:
    url: jdbc:mysql://localhost:3306/finsight_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: finsight_user
    password: finsight_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8080

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  access-token-expiry-ms: 900000       # 15 minutes
  refresh-token-expiry-ms: 604800000   # 7 days

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: finsight-documents

# ?? Qdrant ???????????????????????????????????????????????????????????
qdrant:
  host: localhost
  port: 6334
  collection-name: finsight_chunks


langchain4j:
  open-ai:
    api-key: ${OPENAI_API_KEY}
    chat-model:
      model-name: gpt-4o-mini
      temperature: 0.0
      max-tokens: 1000
    embedding-model:
      model-name: text-embedding-3-small

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.finsight: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
